main: ml.pkom.skwindow.Mod
name: SkWindow
description: "SkWindow is Skript Addon. If add this addon, You can write script of Skript easily."
version: "1.0.0"
author: "Pitan_MAD"
website: "http://pkom.ml/?Minecraft/Spigot/%E8%87%AA%E4%BD%9C%E3%83%97%E3%83%A9%E3%82%B0%E3%82%A4%E3%83%B3"
depend: [Skript]
commands:
  ellipsisk:
    description: "Show information of SkWindow to player"
    usage: "/skwindow"